/**
 * Writes public/sitemap.xml and public/robots.txt before the Vite build so
 * both are copied into dist/ as static files.
 *
 *   npm run generate:seo   (also runs automatically via prebuild)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { routes, site, absoluteUrl } from './routes.mjs';
import { products } from '../src/data/products.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = path.join(root, 'public');

const xmlEscape = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const urlEntries = routes
  .map(
    (r) => `  <url>
    <loc>${xmlEscape(absoluteUrl(r.path))}</loc>
    <lastmod>${r.lastmod}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
    <image:image>
      <image:loc>${xmlEscape(absoluteUrl(r.image))}</image:loc>
      <image:title>${xmlEscape(r.title)}</image:title>
    </image:image>
  </url>`,
  )
  .join('\n');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${urlEntries}
</urlset>
`;

const robots = `# robots.txt for ${site.url}
User-agent: *
Allow: /
Disallow: /404

# Common SEO crawlers are welcome; adjust if crawl budget becomes an issue.
User-agent: AhrefsBot
Crawl-delay: 10

User-agent: SemrushBot
Crawl-delay: 10

Sitemap: ${site.url}/sitemap.xml
`;

// Product pages used to live at /products/<numeric id>. Those URLs may be
// indexed or linked from elsewhere, so redirect them permanently to the
// keyword slug rather than relying on the client-side fallback.
const legacyRedirects = products
  .map((p) => `/products/${p.id}    /products/${p.slug}    301!`)
  .join('\n');

const redirects = `# Generated by scripts/generate-sitemap.mjs — do not edit by hand.
# Legacy numeric product URLs → keyword slugs.
${legacyRedirects}

# SPA fallback. Listed last so real files and the rules above win first.
/*    /index.html    200
`;

fs.mkdirSync(publicDir, { recursive: true });
fs.writeFileSync(path.join(publicDir, 'sitemap.xml'), sitemap);
fs.writeFileSync(path.join(publicDir, 'robots.txt'), robots);
fs.writeFileSync(path.join(publicDir, '_redirects'), redirects);

console.log(`[seo] sitemap.xml written with ${routes.length} URLs`);
console.log('[seo] robots.txt written');
console.log(`[seo] _redirects written with ${products.length} legacy product redirects`);
